### ISSUE TITLE
ElNotification 没有样式 MessageBox 报警告

### ISSUE THREAD

**Issue by ghost** [sxzz/element-plus-best-practices#1]
ElNotification 没有样式
MessageBox 报警告

**Comment by sxzz** [comment]
请详述。

**Comment by ghost** [comment]
有的时候自动加载组件有延迟，导致样式没有自动引入；
表格 横纵内容过多时，固定列和表头无法自动引入el-scrollbar的样式，导致表格无法滚动

**Comment by sxzz** [comment]
问题1，请提供一个最小可复现仓库
问题2，请到Element Plus主仓库反馈（如有issue就不用重复发了）

**Comment by ghost** [comment]
https://gitee.com/zhoutongg/element-plus-best-practices-main__table-test
提供一个gitee库，github访问有点慢
