### ISSUE TITLE
vite.config.js

### ISSUE THREAD

**Issue by zhengyimeng** [sxzz/element-plus-best-practices#7]
### Describe the bug

prefix 配置问题
<img width="494" alt="image" src="https://user-images.githubusercontent.com/20783425/196582240-8582ea79-a0e3-4fd5-b196-3e5a424cd8f8.png">

### Reproduction

x

### System Info

```Shell
macos
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhengyimeng** [comment]
prefix 应该放在 components 里，而不是 authimport
否则没有效果

**Comment by sxzz** [comment]
模板(components) 的前缀默认为 i，不需要修改。
API(auto-import) 的前缀更改为 `Icon`，例如 `console.log(IconEpAim)`。
